import {StyleSheet, Dimensions} from 'react-native';

export const styles = StyleSheet.create({
  background: {
    backgroundColor: 'white',
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'flex-start',
    alignItems: 'stretch',
    alignContent: 'center',
  },
  backgroundLanguage: {
    backgroundColor: 'white',
    flex: 1,
    flexDirection: 'column',
    paddingHorizontal: 30,
  },
  main: {
    width: '100%',
    height: 140,
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    alignItems: 'center',
  },
  fourTouchables: {
    width: '44%',
    height: '87%',
  },
  fourTouchablesBasic: {
    width: '100%',
    height: 345,
  },
  fourtouchableImage: {
    resizeMode: 'contain',
    borderRadius: 10,
    backgroundColor: 'white',
    width: (Dimensions.get('screen').width * 43.29) / 100,
  },
  checkbox: {
    alignSelf: 'center',
  },
  attractionsTitle: {
    height: 30,
    justifyContent: 'center',
    top: 3,
  },
  homeScreen: {
    width: '100%',
    height: Dimensions.get('screen').height / 1.224,
    backgroundColor: '#E6E6E6',
    flexDirection: 'column',
    alignItems: 'flex-start',
  },
  attractionsTitleFont: {
    fontSize: 18,
  },
  attractionsViews: {
    height: Dimensions.get('screen').height / 4.25,
    backgroundColor: '#EEEFF4',
  },
  attractionsSearchPart: {
    height: 60,
    width: '100%',
    backgroundColor: 'white',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: (Dimensions.get('screen').width * 4.28) / 100,
    borderColor: '#D9DBDC',
    borderBottomWidth: 0.7,
    borderTopWidth: 1,
  },
  AttractionMapFilter: {
    borderColor: '#D9DBDC',
    borderRadius: 30,
    height: 40,
    width: 240,
    borderWidth: 0.5,
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    alignItems: 'center',
  },
  AtractionIcons: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  AttractionFilterMapText: {
    fontSize: 15,
    fontWeight: '500',
    color: '#303030',
  },
  attractionSearchFilterImages: {
    resizeMode: 'contain',
    borderRadius: 10,
    height: 28,
    width: 28,
  },
  attractionBookmarkImages: {
    height: 25,
    width: 25,
  },
  favorites: {
    height: Dimensions.get('screen').height / 1.418,
    width: '100%',
  },
  noFavorites: {
    height: 600,
    width: '100%',
    alignItems: 'center',
    top: 20,
  },
  noFavoritesText: {
    fontSize: 25,
    color: '#00115C',
  },
  filters: {
    height: Dimensions.get('screen').height / 1.418,
    width: '100%',
    flexDirection: 'row',
    backgroundColor: '#EEEFF4',
  },
  fitered: {
    height: Dimensions.get('screen').height / 1.457,
    width: '100%',
  },
  mapPart: {
    height: Dimensions.get('screen').height / 1.457,
    width: '100%',
    alignItems: 'center',
  },
  map: {
    height: 584,
    width: '100%',
  },
  mapCallout: {
    heigth: 150,
    width: 390,
    flexDirection: 'row',
    backgroundColor: 'white',
    position: 'absolute',
  },
  mapImage: {
    heigh: 100,
    width: 80,
  },
  mapCalloutHours: {
    flexDirection: 'row',
    width: 175,
    height: 130,
    justifyContent: 'center',
    alignItems: 'center',
  },
  mapCalloutHoursText: {
    color: '#3AB94F',
    fontSize: 15,
  },
  mapCalloutHoursImage: {
    resizeMode: 'contain',
    height: 18,
    width: 18,
  },
  searchPart: {
    height: Dimensions.get('screen').height / 1.32,
    width: '100%',
  },
  search_Attractions: {
    height: 51,
    width: '100%',
    flexDirection: 'row',
    borderColor: '#D9DBDC',
    borderBottomWidth: 0.5,
    borderTopWidth: 1,
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  searchInputPart: {
    height: Dimensions.get('screen').width * 0.0891,
    width: (Dimensions.get('screen').width * 81.48) / 100,
    borderRadius: 30,
    flexDirection: 'row',
    backgroundColor: '#E6E6E6',
    alignItems: 'center',
    justifyContent: 'space-evenly',
  },
  searchInput: {
    height: Dimensions.get('screen').height * 0.5092,
    width: Dimensions.get('screen').width * 0.6875,
    textAlign: 'left',
    paddingTop: 0,
    paddingBottom: 0,
  },
  searchInputBackIcon: {
    resizeMode: 'contain',
    borderRadius: 10,
    height: 30,
    width: 30,
  },
  searchPartFlatList: {
    height: 580,
    width: '100%',
    alignItems: 'center',
  },
  languages: {
    height: 35,
    width: '100%',
    justifyContent: 'center',
  },
  languagesSeparateView: {
    height: 1,
    width: '100%',
    backgroundColor: '#313233',
    opacity: 0.13,
  },
  languagesTouchable: {
    height: 33,
    width: 300,
    justifyContent: 'space-between',
    alignItems: 'center',
    flexDirection: 'row',
  },
  categoriesOfAttraction: {
    height: 130,
    width: '100%',
    backgroundColor: 'white',
    alignItems: 'center',
    justifyContent: 'space-evenly',
    flexDirection: 'row',
    borderRadius: 20,
  },
  categoriesOfFilter: {
    height: 390,
    width: '100%',
    backgroundColor: 'white',
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'flex-start',
    borderRadius: 20,
  },
  attractionIconFocused: {
    color: '#FF8600',
  },
  attractionIcon: {
    color: '#1D1F27',
  },
  SelectedCategoriesItems: {
    height: 25,
    borderColor: '#00115C',
    borderWidth: 0.5,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 5,
    marginHorizontal: 5,
    backgroundColor: 'white',
  },
  SelectedCategoriesItemsText: {
    color: '#00115C',
    fontSize: 15,
    fontWeight: '500',
  },
  imageWrapperAndroid: {
    height: 200,
    flex: 1,
    marginTop: -85,
    width: 330,
  },
  selectedFilters: {
    height: 33,
    width: '100%',
    backgroundColor: 'white',
    opacity: 0.8,
    zIndex: 2,
    position: 'absolute',
    alignItems: 'flex-start',
    alignSelf: 'center',
    paddingLeft: 10,
  },
  bigUglyOrangeButton: {
    height: 50,
    width: '100%',
    backgroundColor: 'orange',
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'flex-start',
    marginVertical: 20,
    borderRadius: 5,
  },
  AttractionTitlePartAllAttractionsEn: {
    left: Dimensions.get('screen').width * 0.7384,
    position: 'absolute',
  },
  AttractionTitlePartAllAttractionsFr: {
    left: Dimensions.get('screen').width * 0.6365,
    position: 'absolute',
  },
  AttractionTitlePartAllAttractionsDe: {
    left: Dimensions.get('screen').width * 0.71,
    position: 'absolute',
  },
  filtersTitle: {
    fontWeight: '400',
    color: '#00115C',
    fontSize: Dimensions.get('screen').width * 0.03055,
  },
  filtersTitleSelected: {
    fontWeight: '400',
    color: 'orange',
    fontSize: Dimensions.get('screen').width * 0.03055,
  },
  filtercategoriesNotSelectedTextView: {
    height: 20,
    width: Dimensions.get('screen').width * 0.3183,
    alignItems: 'center',
    justifyContent: 'flex-start',
    alignSelf: 'flex-start',
  },
  filterPartScrollView: {
    marginHorizontal: 10,
    height: Dimensions.get('screen').height * 0.7051,
    width: '100%',
  },
  filterPartCategories: {
    height: Dimensions.get('screen').height * 0.4583,
    width: '100%',
    backgroundColor: 'white',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 10,
  },
  filterCategoriesnotSelected: {
    height: Dimensions.get('screen').height * 0.1175,
    width: Dimensions.get('screen').width * 0.3183,
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  filterCategoriesSelected: {
    height: Dimensions.get('screen').height * 0.1175,
    width: Dimensions.get('screen').width * 0.3183,
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  filtercategoriesSelectedTextView: {
    height: Dimensions.get('screen').height * 0.0235,
    width: Dimensions.get('screen').width * 0.3182,
    alignItems: 'center',
    justifyContent: 'flex-start',
    alignSelf: 'flex-start',
  },
  languageText: {
    fontWeight: '600',
  },
});
